project_id = "gahtggchbnrliczsfaqf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[functions.telegram-auth]
verify_jwt = false

[realtime]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324

[edge_runtime]
enabled = true
inspector_port = 8083

[analytics]
enabled = false

[supabase_cli]
update_check = false