// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gahtggchbnrliczsfaqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhaHRnZ2NoYm5ybGljenNmYXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTIzNzMsImV4cCI6MjA2ODY2ODM3M30.-2LgNgniHV5Do8_gdoXLswjZ8P8u-4fRQzZxv3qs3kQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});