// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enualwijtpsaurhcdorj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVudWFsd2lqdHBzYXVyaGNkb3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Mjg4MjIsImV4cCI6MjA2ODUwNDgyMn0.MCyFyRTkQmS2yGhjo3XUt-uoW42X73wp05QDKd_R0KQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage, // Изменено на sessionStorage для хранения только в рамках сессии
    persistSession: true,
    autoRefreshToken: true,
  }
});